### ISSUE TITLE
Proposal: ht cron

### ISSUE THREAD

**Issue by SchumacherFM** [vdobler/ht#19]
Use case: I would like to test if an ecommerce website has between Friday and Saturday for certain URLs (products) new prices and from Sunday on restored the old prices. Those prices are in the product listing and on the product detail page, etc. 
If the tests fail I got notified via email, slack, twitter, carrier pigeon ...

The old command to execute such a test:
```
$ ht_darwin exec -output ./system-integration/reports/ -Dfile ./system-integration/env/local.json ./system-integration/product_listing/...
```

The new command could be for example

```
$ ht_darwin cron -config mycron.hjson -Dfile ./system-integration/env/local.json &
```

Starts ht_darwin in the background and keeps it running until killed or handled via supervisord.

The `mycron.hjson` contains the cron expression when to execute which test suite, a path to the test suite)

For example:

```json
{
    "Tests": [
        {
            "Name": "cron test new prices",
            "CronExpression": "0 2 * * 5,6",
            "Suite": "./system-integration/product_listing/...",
            "Variables": {
                "SKU_321654987_PRICE": 324.45,
            },
            "report": ["email1","slackA"]
        },
        {
            "Name": "cron test old prices",
            "CronExpression": "0 2 * * 7",
            "Suite": "./system-integration/product_listing/...",
            "Variables": {
                "SKU_321654987_PRICE": 399.95,
            },
            "report": "email2",
        },
    ],
    "email1": {
        "type": "email",
        "smtp": "smtp.gmail.com",
        "user": "hans",
        "password": "uhu34hifhqief",
    },
    "email2": {
        "type": "email",
        "smtp": "smtp.gmail.com",
        "user": "hans",
        "password": "uhu34hifhqief",
    },
    "slackA": {
        "type": "slack",
        "TOKEN": "30205ead7bbe0b88c56d4005edb8ceff"
    },
}
```

Might there be another way to achieve this, an easier via e.g. Unix command line tools?
Any other ideas or just crap?

**Comment by vdobler** [comment]
I admit I do not understand why each program has to bring its own crontab.
If someone wants to run things regularly its

    man 5 crontab
    crontab -e
    tap tap tap ...
    Esc :wg

Maybe one has to provide a little wrapper script (but this is easy testable).

Which works, is bug free and does the emailing.
Transporting the emails to some remote account is more work and Slack integration has to be done manually. (But personally I find this use-slack-for-everything pretty strange.) Or have the wrapper script do the emailing / slacking.

Letting crond do the work has one more advantage: If the program run regularly crashes it is rerun by cron (and might not crash the next time). If the program has builtin cron support it must not crash (and not be killed by the oom killer).

(If some deeply encapsulated functionality _inside_ and application needs to be scheduled regularly this might be different, but the case here is a basically a full invocation of a program).

So I'm inclined to say: Use your crond and crontab or launchd on Mac which is only a bit more XML.

**Comment by SchumacherFM** [comment]
Thank you for the answer. I've nearly had the same thoughts but wasn't sure.
