### ISSUE TITLE
Not resolvable variable is not reported

### ISSUE THREAD

**Issue by gdmn** [vdobler/ht#2]
Assuming _PRODUCTURL_ is not defined (i.e. not listed in "**Variables**" section during test execution), incorrect request is made:

```
GET https://xxxx:9002/.%7B%7BPRODUCTURL%7D%7D
```

_Expected_: Error message should be displayed.

**Comment by vdobler** [comment]
Technically https://xxxx:9002/.%7B%7BPRODUCTURL%7D%7D is a valid URL.
If any occurrence of {{NAME}} would be treated as error if NAME is not a defined variable than it would be impossible to call URLs (or sending body with) containing {{NAME}}. Which is as problematic than not reporting an error. The only possible workaround would be to set NAME="{{NAME}}" (as substitutions are not recursive). But such a workaround is even more ugly than the "missing" error value.

So won't fix. Occurences of patterns of the form {{NAME}} are replaced by a certain value iff a variable NAME is defined. It is not the case that {{NAME}} actually **is** a variable reference.
