### ISSUE TITLE
RepsonseBody with correct file extension

### ISSUE THREAD

**Issue by SchumacherFM** [vdobler/ht#4]
https://github.com/vdobler/ht/blob/f4a52f633aad0d41a380b03b86bb1d768553d94a/ht/report.go#L557

Are you open for the feature to extend the written file `MainTest-XX.ResponseBody` with the correct file extension depending on the content type?

E.g. `MainTest-04.ResponseBody.json` for pure JSON responses; `MainTest-04.ResponseBody.html` for HTML docs ... would be easier to open the files with the correct tools in an operating system.

**Comment by vdobler** [comment]
Done.

**Comment by SchumacherFM** [comment]
Thank you! 👏
