### ISSUE TITLE
Feature: Connection Timing information

### ISSUE THREAD

**Issue by SchumacherFM** [vdobler/ht#5]
I would like to see a report which states the timing information of a network request.

Hopefully this feature fits into your sprint planning process ;-)

https://twitter.com/davecheney/status/779269890918146048

![ctcfzpduiaqizdf](https://cloud.githubusercontent.com/assets/372027/18783817/6e442a44-818e-11e6-896e-c11eccddca4a.jpg)

Printscreen from the Chrome Network Panel

![screen shot 2016-09-23 at 13 03 50](https://cloud.githubusercontent.com/assets/372027/18783818/6e480ca4-818e-11e6-83c5-399bbdacaf69.png)

**Comment by vdobler** [comment]
That will be a major pain in the ... as this requires dissecting `http.Do` into it's various steps.

**Comment by SchumacherFM** [comment]
It really looks like PITA https://github.com/davecheney/httpstat/blob/master/main.go#L98 😕

but what about: https://golang.org/pkg/net/http/httptrace/

Otherwise: close this issue.

**Comment by SchumacherFM** [comment]
After discussions a check for TTFB would be perfect.

**Comment by SchumacherFM** [comment]
Has this already been implemented a check and report for TTFB?

**Comment by SchumacherFM** [comment]
Won't fix.
