### ISSUE TITLE
Replace Otto with goja

### ISSUE THREAD

**Issue by SchumacherFM** [vdobler/ht#7]
https://github.com/dop251/goja

- Full ECMAScript 5.1 support (yes, including regex and strict mode).
- Passes nearly all tc39 tests tagged with es5id. The goal is to pass all of them.
- On average 6-7 times faster than otto. Also uses considerably less memory.

;-)

**Comment by marcin-ptaszynski** [comment]
Hi @SchumacherFM , we're experiencing performance problems with otto. Could you share, why you've decided not to migrate to goja after all (ht master still vendors otto even after this issue has been closed)?

**Comment by vdobler** [comment]
@marcin-ptaszynski Are you experiencing performance problems with ht because of otto or are you unsatisfied with otto "outside" of ht?
You know: The performance of the JS-interpreter has absolutely no impact on ht.

**Comment by marcin-ptaszynski** [comment]
Hi @vdobler, I have no performance problem with ht. I was just googling around for other people's experiences with goja and stumbled upon this issue and it got me to wonder. If ottos performance doesn't impact ht, then I guess you didn't have much reason to migrate to goja.

**Comment by SchumacherFM** [comment]
We have not yet used intensively the JS features of ht. But even then I think switching from otto to goja is negligible. The pages which ht should test have a more worse overall performance than otto ;-)
If a tested page would return below 1ms then maybe we can start thinking about replacing otto ;-)

**Comment by marcin-ptaszynski** [comment]
@SchumacherFM , thanks
