### ISSUE TITLE
Copy as CURL in report html

### ISSUE THREAD

**Issue by SchumacherFM** [vdobler/ht#9]
See printscreen

![screen shot 2016-12-06 at 11 28 53](https://cloud.githubusercontent.com/assets/372027/20922257/cd8b4a2a-bba7-11e6-9ba0-aed1a8c4894d.png)

Idea to convert http.Request into curl: https://github.com/moul/http2curl/blob/master/http2curl.go

**Comment by SchumacherFM** [comment]
No need for fancy javascript to copy the command into the clipboard but a simple pre-formatted text field would be enough.

**Comment by vdobler** [comment]
http2curl.go is incomplete and buggy, a bad combination...

**Comment by SchumacherFM** [comment]
That's why I've written "Idea" 😜

**Comment by SchumacherFM** [comment]
Thanks! 👏
